CREATE DATABASE SmartRide;
USE SmartRide;

CREATE TABLE Users(
ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Email VARCHAR (50) UNIQUE NOT NULL,
Contact VARCHAR(14) NOT NULL,
Gender VARCHAR(10),
Role VARCHAR(10) NOT NULL
);

CREATE TABLE Drivers(
ID INT AUTO_INCREMENT PRIMARY KEY,
UserID INT,
VehicleRegistration VARCHAR(10),
FOREIGN KEY (UserID) REFERENCES Users(ID)
);

ALTER TABLE Profile
DROP FOREIGN KEY profile_ibfk_1;
SHOW CREATE TABLE Profile;

SET SQL_SAFE_UPDATES = 0;
CREATE TABLE Passwords(
ID INT AUTO_INCREMENT PRIMARY KEY,
UserID INT,
Password VARCHAR(18) UNIQUE,
FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE Profile(
ID INT AUTO_INCREMENT PRIMARY KEY,
UserID INT,
Name VARCHAR(50),
Contact VARCHAR(14) UNIQUE,
Email VARCHAR(50) UNIQUE,
Address VARCHAR(100),
City VARCHAR(50),
FOREIGN KEY (UserID) REFERENCES Users(ID)
);
SELECT * FROM Profile;
SELECT * FROM Users;
CREATE TABLE OTPs(
ID INT AUTO_INCREMENT PRIMARY KEY,
UserID INT,
OTP INT,
FOREIGN KEY (UserID) REFERENCES Users(ID)
);
SELECT * FROM Users;

CREATE TABLE Wallet(
  WalletID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Balance DECIMAL(10,2) DEFAULT 0,
  UpdatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(ID)
);
SELECT * FROM Wallet;
SELECT * FROM WalletTransactions;
DELETE FROM Wallet;
CREATE TABLE WalletTransactions(
  TranactionID INT AUTO_INCREMENT PRIMARY KEY,
  WalletID INT,
  Amount DECIMAL(10,2),
  Type ENUM('CREDIT','DEBIT') DEFAULT 'CREDIT',
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (WalletID) REFERENCES Wallet(WalletID)
);

