CREATE DATABASE SmartRide;
USE SmartRide;

CREATE TABLE Users(
ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Email VARCHAR (50) UNIQUE NOT NULL,
Contact VARCHAR(14) NOT NULL,
Gender VARCHAR(10),
Role VARCHAR(10) NOT NULL
);

CREATE TABLE Passwords(
ID INT AUTO_INCREMENT PRIMARY KEY,
UserID INT,
Password VARCHAR(18) UNIQUE,
FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE Profile(
ID INT AUTO_INCREMENT PRIMARY KEY,
UserID INT,
Name VARCHAR(50),
Contact VARCHAR(14) UNIQUE,
Email VARCHAR(50) UNIQUE,
Address VARCHAR(100),
City VARCHAR(50),
FOREIGN KEY (UserID) REFERENCES Users(ID)
);